//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediProject_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PeopleList", Namespace="http://schemas.datacontract.org/2004/07/MediProject_Server.Model", ItemName="Person")]
    [System.SerializableAttribute()]
    public class PeopleList : System.Collections.Generic.List<MediProject_Server.Model.Person> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MedicationsList", Namespace="http://schemas.datacontract.org/2004/07/MediProject_Server.Model", ItemName="Medication")]
    [System.SerializableAttribute()]
    public class MedicationsList : System.Collections.Generic.List<MediProject_Server.Model.Medication> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="KupatHolimList", Namespace="http://schemas.datacontract.org/2004/07/MediProject_Server.Model", ItemName="KupatHolim")]
    [System.SerializableAttribute()]
    public class KupatHolimList : System.Collections.Generic.List<MediProject_Server.Model.KupatHolim> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserList", Namespace="http://schemas.datacontract.org/2004/07/MediProject_Server.Model", ItemName="User")]
    [System.SerializableAttribute()]
    public class UserList : System.Collections.Generic.List<MediProject_Server.Model.User> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPeople", ReplyAction="http://tempuri.org/IService1/GetAllPeopleResponse")]
        MediProject_Client.ServiceReference1.PeopleList GetAllPeople();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPeople", ReplyAction="http://tempuri.org/IService1/GetAllPeopleResponse")]
        System.Threading.Tasks.Task<MediProject_Client.ServiceReference1.PeopleList> GetAllPeopleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUser", ReplyAction="http://tempuri.org/IService1/InsertUserResponse")]
        void InsertUser(MediProject_Server.Model.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUser", ReplyAction="http://tempuri.org/IService1/InsertUserResponse")]
        System.Threading.Tasks.Task InsertUserAsync(MediProject_Server.Model.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllKupas", ReplyAction="http://tempuri.org/IService1/GetAllKupasResponse")]
        MediProject_Client.ServiceReference1.KupatHolimList GetAllKupas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllKupas", ReplyAction="http://tempuri.org/IService1/GetAllKupasResponse")]
        System.Threading.Tasks.Task<MediProject_Client.ServiceReference1.KupatHolimList> GetAllKupasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsers", ReplyAction="http://tempuri.org/IService1/GetAllUsersResponse")]
        MediProject_Client.ServiceReference1.UserList GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsers", ReplyAction="http://tempuri.org/IService1/GetAllUsersResponse")]
        System.Threading.Tasks.Task<MediProject_Client.ServiceReference1.UserList> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMedications", ReplyAction="http://tempuri.org/IService1/GetAllMedicationsResponse")]
        MediProject_Client.ServiceReference1.MedicationsList GetAllMedications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMedications", ReplyAction="http://tempuri.org/IService1/GetAllMedicationsResponse")]
        System.Threading.Tasks.Task<MediProject_Client.ServiceReference1.MedicationsList> GetAllMedicationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserMedications", ReplyAction="http://tempuri.org/IService1/GetUserMedicationsResponse")]
        MediProject_Client.ServiceReference1.MedicationsList GetUserMedications(MediProject_Server.Model.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserMedications", ReplyAction="http://tempuri.org/IService1/GetUserMedicationsResponse")]
        System.Threading.Tasks.Task<MediProject_Client.ServiceReference1.MedicationsList> GetUserMedicationsAsync(MediProject_Server.Model.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMedication", ReplyAction="http://tempuri.org/IService1/AddMedicationResponse")]
        void AddMedication(MediProject_Server.Model.User user, MediProject_Server.Model.Medication medication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMedication", ReplyAction="http://tempuri.org/IService1/AddMedicationResponse")]
        System.Threading.Tasks.Task AddMedicationAsync(MediProject_Server.Model.User user, MediProject_Server.Model.Medication medication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MediProject_Server.CompositeType GetDataUsingDataContract(MediProject_Server.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MediProject_Server.CompositeType> GetDataUsingDataContractAsync(MediProject_Server.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MediProject_Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MediProject_Client.ServiceReference1.IService1>, MediProject_Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MediProject_Client.ServiceReference1.PeopleList GetAllPeople() {
            return base.Channel.GetAllPeople();
        }
        
        public System.Threading.Tasks.Task<MediProject_Client.ServiceReference1.PeopleList> GetAllPeopleAsync() {
            return base.Channel.GetAllPeopleAsync();
        }
        
        public void InsertUser(MediProject_Server.Model.User user) {
            base.Channel.InsertUser(user);
        }
        
        public System.Threading.Tasks.Task InsertUserAsync(MediProject_Server.Model.User user) {
            return base.Channel.InsertUserAsync(user);
        }
        
        public MediProject_Client.ServiceReference1.KupatHolimList GetAllKupas() {
            return base.Channel.GetAllKupas();
        }
        
        public System.Threading.Tasks.Task<MediProject_Client.ServiceReference1.KupatHolimList> GetAllKupasAsync() {
            return base.Channel.GetAllKupasAsync();
        }
        
        public MediProject_Client.ServiceReference1.UserList GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<MediProject_Client.ServiceReference1.UserList> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public MediProject_Client.ServiceReference1.MedicationsList GetAllMedications() {
            return base.Channel.GetAllMedications();
        }
        
        public System.Threading.Tasks.Task<MediProject_Client.ServiceReference1.MedicationsList> GetAllMedicationsAsync() {
            return base.Channel.GetAllMedicationsAsync();
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MediProject_Client.ServiceReference1.MedicationsList GetUserMedications(MediProject_Server.Model.User user) {
            return base.Channel.GetUserMedications(user);
        }
        
        public System.Threading.Tasks.Task<MediProject_Client.ServiceReference1.MedicationsList> GetUserMedicationsAsync(MediProject_Server.Model.User user) {
            return base.Channel.GetUserMedicationsAsync(user);
        }
        
        public void AddMedication(MediProject_Server.Model.User user, MediProject_Server.Model.Medication medication) {
            base.Channel.AddMedication(user, medication);
        }
        
        public System.Threading.Tasks.Task AddMedicationAsync(MediProject_Server.Model.User user, MediProject_Server.Model.Medication medication) {
            return base.Channel.AddMedicationAsync(user, medication);
        }
        
        public MediProject_Server.CompositeType GetDataUsingDataContract(MediProject_Server.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MediProject_Server.CompositeType> GetDataUsingDataContractAsync(MediProject_Server.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
